Admin.create(name: 'fashion', password: 'fashionable')

User.create(name: 'Guest User', username: '@user', email: 'user@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', zip: '0000000', prefecture: '東京都', city: '〇〇区', street: '〇〇町', address: '東京都〇〇区〇〇町', tel: '0000000000', profile: '', activated: true, photo: File.open("./public/image/skull.png"))
User.create(name: 'Dragon', username: '@dragon', image:File.open("./public/image/dragon.png"), email: 'dragon@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', zip: '0000000', prefecture: '東京都', city: '〇〇区', street: '〇〇町', address: '東京都〇〇区〇〇町', tel: '0000000000', profile: '幻獣系デザイナーのドラゴンです。よろしくお願いします。', activated: true)
User.create(name: 'Gorilla', username: '@gorilla', image:File.open("./public/image/gorilla.png"), email: 'gorilla@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', zip: '0000000', prefecture: '東京都', city: '〇〇区', street: '〇〇町', address: '東京都〇〇区〇〇町', tel: '0000000000', profile: '筋肉系デザイナーのゴリラです。よろしくお願いします。', activated: true)
User.create(name: 'Panda', username: '@panda', image:File.open("./public/image/panda.png"), email: 'panda@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', zip: '0000000', prefecture: '東京都', city: '〇〇区', street: '〇〇町', address: '東京都〇〇区〇〇町', tel: '0000000000', profile: '珍獣系デザイナーのパンダです。よろしくお願いします。', activated: true)
User.create(name: 'Cat', username: '@cat', image:File.open("./public/image/cat.png"), email: 'cat@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', zip: '0000000', prefecture: '東京都', city: '〇〇区', street: '〇〇町', address: '東京都〇〇区〇〇町', tel: '0000000000', profile: 'キュート系デザイナーのキャットです。よろしくお願いします。', activated: true)
User.create(name: 'Penguin', username: '@penguin', image:File.open("./public/image/penguin.png"), email: 'penguin@example.com', password: 'aaaaaaaa', password_confirmation: 'aaaaaaaa', zip: '0000000', prefecture: '東京都', city: '〇〇区', street: '〇〇町', address: '東京都〇〇区〇〇町', tel: '0000000000', profile: '癒し系デザイナーのペンギンです。よろしくお願いします。', activated: true)
Cart.create(user_id: 1)
Cart.create(user_id: 2)
Cart.create(user_id: 3)
Cart.create(user_id: 4)
Cart.create(user_id: 5)
Cart.create(user_id: 6)

WorkCat.create(name: 'トップス')
WorkCat.create(name: 'パンツ')
WorkCat.create(name: 'スカート')
WorkCat.create(name: 'ワンピース・ドレス')
WorkCat.create(name: 'サロペット・オールインワン')
WorkCat.create(name: 'セットアップアイテム')
WorkCat.create(name: 'アウター')
WorkCat.create(name: 'バッグ')
WorkCat.create(name: 'シューズ')
WorkCat.create(name: '帽子')
WorkCat.create(name: 'ファッション小物')
WorkCat.create(name: '財布・小物')
WorkCat.create(name: 'アクセサリー')
WorkCat.create(name: 'ヘアアクセサリー')

Work.create(work_cat_id: 7, title: 'こま１', price:'13900', text: '素材に〇〇を使い、着心地の良い仕上がりになっています。流行の〇〇スタイルと独自のデザインを織り交ぜています。', onlyone: 0, status: 1, image:File.open("./public/image/koma1.png"))
Work.create(work_cat_id: 7, title: 'こま２', price:'13900', text: '素材に〇〇を使い、着心地の良い仕上がりになっています。流行の〇〇スタイルと独自のデザインを織り交ぜています。', onlyone: 0, status: 1, image:File.open("./public/image/koma2.png"))
Work.create(work_cat_id: 7, title: 'こま３', price:'14900', text: '素材に〇〇を使い、着心地の良い仕上がりになっています。流行の〇〇スタイルと独自のデザインを織り交ぜています。', onlyone: 0, status: 1, image:File.open("./public/image/koma3.png"))
Work.create(work_cat_id: 7, title: 'こま４', price:'16900', text: '素材に〇〇を使い、着心地の良い仕上がりになっています。流行の〇〇スタイルと独自のデザインを織り交ぜています。', onlyone: 0, status: 1, image:File.open("./public/image/koma4.png"))
Work.create(work_cat_id: 7, title: 'こま５', price:'16900', text: '素材に〇〇を使い、着心地の良い仕上がりになっています。流行の〇〇スタイルと独自のデザインを織り交ぜています。', onlyone: 0, status: 1, image:File.open("./public/image/koma5.png"))

ArticleCat.create(name: '旅')
ArticleCat.create(name: 'インスピレーション')

Article.create(article_cat_id: 2, image:File.open("./public/image/koma1.png"), title: 'AIによるファッションデザイン', image_title: 'AIによるファッションデザインの例', text: 'AIの力を借りたファッションデザインが注目を集めています。従来の枠にとらわれない斬新なアイデアやデザインが生まれ、新たなトレンドを作り出しています。AIは膨大なデータを分析し、傾向や顧客の好みを把握することで、デザイナーに新たなインスピレーションをもたらします。これにより、より多様性のあるファッションが生まれ、個々のスタイルに合った選択肢が提供されることでしょう。')
Article.create(article_cat_id: 1, image:File.open("./public/image/koma2.png"), title: '北海道旅行で感じたこと', image_title: 'ジンギスカン鍋', text: '北海道の広大な大地と澄み切った空気に心洗われた。緑豊かな大自然の中で、のどかに草を食む牛たちを眺めながら、新鮮な食材を堪能。日常を忘れる旅だった。')
Article.create(article_cat_id: 1, image:File.open("./public/image/koma3.png"), title: '京都の歴史の深さ', image_title: '京都の小道', text: '古都京都を歩くと、その歴史の深さに圧倒される。石畳の小道、数百年の時を経た寺社の佇まい。一歩一歩に物語が刻まれ、訪れる者の心を引きつける。')

NewsCat.create(name: '風刺')
NewsCat.create(name: '出来事')

News.create(news_cat_id: 2, image:File.open("./public/image/manga.png"), title: 'キャッシュレスを使い始めた', image_title: '', text: '手のひらに収まるスマホが財布に変わり、購買の瞬間が静かに変貌を遂げた。一振りで支払い完了。紙幣の触感と引き換えに、取引の速さと便利さを手に入れた。')
News.create(news_cat_id: 1, image:File.open("./public/image/manga.png"), title: '今日のお縄', image_title: '', text: '街角で見かける立ち小便。かつては目をつぶられた小さな違反が、今や監視カメラの目に映る。公然わいせつで警察のお世話になる時代。プライバシーの終焉か、秩序の始まりか。')
